# Generated by Django 4.2.1 on 2023-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('spo', 'Sponsor'), ('fac', 'Faculty'), ('stu', 'Student')], max_length=50),
        ),
    ]
