# Generated by Django 4.2.1 on 2023-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('fac', 'Faculty'), ('spo', 'Sponsor'), ('stu', 'Student')], max_length=50),
        ),
    ]
