# Generated by Django 4.2.1 on 2023-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('tech', 'Tech'), ('non-tech', 'Non-Tech'), ('fest', 'Fest')], max_length=10)),
                ('event_description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_banner', models.ImageField(upload_to='uploads/event_banners/')),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('is_highlight', models.BooleanField(default=False)),
            ],
        ),
    ]
