# Generated by Django 4.2.1 on 2023-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('tech', 'Tech'), ('non-tech', 'Non-Tech'), ('fest', 'Fest')], max_length=10)),
                ('event_description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_banner', models.ImageField(upload_to='event_banners/')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('organizer_name', models.CharField(max_length=255)),
                ('organizer_club', models.CharField(blank=True, max_length=255, null=True)),
                ('organizer_phone', models.CharField(max_length=15)),
                ('organizer_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
