# Generated by Django 4.2.1 on 2023-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_event_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
