# Generated by Django 4.2.1 on 2023-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_event_entry_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
